Hotfix: Call-time pass-by-reference has been removed
Error: Call-time pass-by-reference has been removed in /sites/all/modules/custom/image_fupload/image_fupload_imagefield/image_fupload_imagefield.module, line 505